### ISSUE TITLE
Container App Job Deployment GitHub Action

### ISSUE THREAD

**Issue by RP-101** [Azure/container-apps-deploy-action#118]
Is there a similar action for deploying "Container App Jobs"?

- Container App Job
https://learn.microsoft.com/en-us/azure/container-apps/tutorial-event-driven-jobs

- Action that from what I can see only supports "Container Apps":
https://github.com/Azure/container-apps-deploy-action

**Comment by sagarneeldubey** [comment]
I was also looking for such an action for deploying container app jobs, but couldn't find one. I ended up writing a run command that deploys a pre-built image (which was done in a previous step) using az cli command. Sample workflow snippet given below.  The CLI command is under the step named `Deploy to Azure Container App Jobs`

```YAML
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository under GITHUB WORKSPACE ${{ github.sha }}
        uses: actions/checkout@v3
      - name: Login to Azure Container Registry and build-push docker image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE }}:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Deploy to Azure Container App Jobs
        run: |
          az containerapp job update --name ${{ env.CONTAINER_APP }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --image ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE }}:${{ github.sha }}

```
