### ISSUE TITLE
Azure Login insufficient

### ISSUE THREAD

**Issue by jgarplind** [Azure/container-apps-deploy-action#14]
I'm trying to deploy a previously build image, using a pre-defined Service Principal and the below job:

```
  deploy:
    runs-on: ubuntu-latest
    environment: Development
    needs: build-and-push
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          acrName: xxx
          ### Expected to be resolved by azure/login@v1, but reality says otherwise ###
          acrUsername: ${{ secrets.AZURE_CLIENT_ID }}
          acrPassword: ${{ secrets.AZURE_CLIENT_SECRET }}
          #####################################################
          containerAppName: yyy
          resourceGroup: zzz
          imageToDeploy: aaa.azurecr.io/bbb:${{ github.event.head_commit.id }}
```

When not supplying `acrUsername` and `acrPassword`, I get the following error:

> WARNING: The installed extension 'containerapp' is in preview.
**ERROR: Failed to retrieve credentials for container registry. Please provide the registry username and password**
Error: Process completed with exit code 1.

Given the documentation and my previous experience, I would have expected the `Log in to Azure` step to have sufficed.

Any clarifications would be helpful, but since the workaround of providing `acrUsername` and `acrPassword` exists, it is not a pressing matter.

Thank you.
