### ISSUE TITLE
Support generic container registry authentication

### ISSUE THREAD

**Issue by Gordonby** [Azure/container-apps-deploy-action#30]
Currently this action only supports authentication with an Azure Container Registry thats in the same subscription as the container app.

I'd like to be able to specify an `imageToDeploy` path and the credentials that are required to access the image. It could be an Azure Container Registry, a GitHub registry or a private registry that I'm hosting on an endpoint.

In my specific case, it is indeed an Azure Container Registry. However it is not in my subscription, and the subscription the ACR is homed in isn't even in the same tenant.

```output
ERROR: The resource with name '***' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription 'Visual Studio Enterprise Subscription (***)'.
```

I'm providing these parameters and would expect it to work.

```
    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v0
      with:
        resourceGroup: containerapp
        imageToDeploy: mycontainerregistry.azurecr.io/azuredocs/azure-vote-7b3cb867c04385f583d1525cdc95912a2f54e52b
        acrName: mycontainerregistry
        acrUsername: ${{ secrets.REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
        
```
