### ISSUE TITLE
Create secrets as part of container app create/update

### ISSUE THREAD

**Issue by sharathchandramg** [Azure/container-apps-deploy-action#40]
Hi,
I am using the action to deploy the containerapp. 

My containerapp contains some environment variables which are sensitive. Hence I am relying on using containerapp secrets and referring the same in `environmentVariables`.  The action I have currently is as follows:

```
- name: Build and deploy Container App
  uses: azure/container-apps-deploy-action@v1
  with:
    acrName: ${{ env.ACR_NAME }}
    acrUsername: ${{ secrets.ACR_CLIENT_ID }}
    acrPassword: ${{ secrets.ACR_CLIENT_SECRET }}
    imageToDeploy: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
    resourceGroup: ${{ env.RESOURCE_GROUP }}
    containerAppEnvironment: ${{ env.CONTAINER_APP_ENV }}
    containerAppName: ${{ env.CONTAINER_APP }}
    ingress: external
    targetPort: 5000
    disableTelemetry: true
    environmentVariables: "DATABASE_URL=secretref:db-url KEYCLOAK_CLIENT_SECRET=secretref:keycloak-client-secret"
```

It looks like this action will suceed only if the secret already exists. This means that this is more useful in update scenarios.

It would be very convenient if we could have created the secrets as part of the action and then use them within `environmentVariables`. Is this a possibility ?

**Comment by cormacpayne** [comment]
@sharathchandramg Hey Sharath, we don't currently have a convenient way to do this from the arguments you provide as a part of the task, but you should be able to accomplish this by creating a [YAML configuration file](https://learn.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec?tabs=yaml#container-app-examples) and providing it as a part of the `yamlConfigPath` argument:

```yaml
properties:
  configuration:
    secrets:
      - name: mysecret
        value: thisismysecret
      - name: myregistrypassword
        value: I<3containerapps
  template:
    containers:
      - image: nginx
        name: nginx
        env:
          - name: HTTP_PORT
            value: 80
          - name: secret_name
            secretRef: mysecret
```

(I've omitted a lot of required properties to focus on the secrets portion of the YAML file)

You can define your secrets on the Container Application with this file (or in the Portal) and reference them via environment variables by defining the reference to them in the `properties.template.containers.env` property.

Please let me know if this plan doesn't work for you and I'll be happy to help out with alternative routes we can take!
