### ISSUE TITLE
Add action outputs?

### ISSUE THREAD

**Issue by michaeloliverx** [Azure/container-apps-deploy-action#55]
I am looking for a way to get the FQDN of the deployed application.

I used to use the [`azure/webapps-deploy`](https://github.com/Azure/webapps-deploy) action which had an output called `webapp-url` which I could then use to populate the GitHub environments e.g.:
```yaml
  deploy:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "ghcr.io/${{ github.repository }}:latest"
```
