### ISSUE TITLE
Error when updating Container App without Dockerfile

### ISSUE THREAD

**Issue by willvelida** [Azure/container-apps-deploy-action#7]
I have a [GitHub Action workflow](https://github.com/willvelida/aca-dapr-service-invocation/blob/main/.github/workflows/deploy.yml) file that provisions the resources for my container app, and then uses the GitHub Action to update the images to ones that are generated by the GitHub Action. 

I've set up my Container Apps deploy action like so:

```
- name: Build and Deploy Backend Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          appSourcePath: ${{ github.workspace }}/src/MyFrontEnd/MyFrontEnd
          acrName: ${{ steps.getacrname.outputs.acrName }}
          acrUsername: ${{ steps.getacrcreds.outputs.loginName }}
          acrPassword: ${{ steps.getacrcreds.outputs.password }}
          containerAppName: myfrontend
          resourceGroup: ${{ secrets.AZURE_RG}} 
```

I have no Dockerfiles in my C# projects and looking at the runner logs, the image is being built successfully, but the action fails with the following error:

```
Error response from daemon: unexpected error reading Dockerfile: read /var/lib/docker/tmp/docker-builder805887875: is a directory
```

Is one of the following happening?

- Is the Container Apps Deploy Action pulling down Oryx images correctly?
- Is this an error from Oryx itself? (and should I raise an issue there?)
- Am I just being stupid and I have to supply a Dockerfile for each of my projects?
