### ISSUE TITLE
Support configuration of scalers

### ISSUE THREAD

**Issue by heddendorp** [Azure/container-apps-deploy-action#93]
It would be cool to change the min and max instances as well as the scaling behavior in the action.

**Comment by mjanschek** [comment]
This should be possible using a yaml for configuration like

```
[...]
  template:
    containers:
      - image: your_image
        name: your_container_app
    scale:
      minReplicas: 1
      maxReplicas: 3
    rules:
      - name: httpscalingrule
        custom:
          type: http
          metadata:
            concurrentRequests: "50"
[...]
```
